# Generated by Django 4.2.3 on 2024-02-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_kategori_movie_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='videolar/', verbose_name='Video'),
        ),
    ]
